networks:
  billing_net:
    driver: bridge
  attendify_net:
    external: true

services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 30056:80
    volumes:
      - fossbilling:/var/www/html
    networks:
      - billing_net
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: fossbilling
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - billing_net
volumes:
  fossbilling: