# TODO: remove ports for security
services:
# TODO: test if secrets work for mysql
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "30002:3306"
    volumes:
      - mysql_data:/var/lib/mysql # cannot use bind mount because it crashes mysql
      - ./:/docker-entrypoint-initdb.d # MySQL runs all sql scripts alphabetically once => chmod 644
# TODO: remove pma because of security issues
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "30003:80"
    depends_on:
        - mysql

# rabbitmq does not support secrets
  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: attendify
      RABBITMQ_DEFAULT_VHOST: attendify
    ports:
      - "30000:15672"
      - "30001:5672"
    volumes:
      - /home/ehbstudent/volumes/rabbitmq:/var/lib/rabbitmq

volumes:
  mysql_data:
