networks:
  attendify_net:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: attendify
      RABBITMQ_DEFAULT_VHOST: attendify
    ports:
      - "${RABBITMQ_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_PORT}:5672"
    volumes:
      - ./rabbitmq/volumes/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - attendify_net